services:
  locust:
    build: locust/
    hostname: locusthost
    ports:
      - "8089:8089"
    environment:
      - LOCUST_FILE=locustfile.py
      - LOCUST_MODE=standalone
      - LOCUST_TARGET_URL=http://kong:8000
    networks:
      - public_net
    depends_on:
      - kong-dbless

  clientes:
    build: clientes/
    hostname: clientehost
    ports:
      - "3000:3000"
    environment:
      - VERSION=1.0
      - MONITOR_PATH=http://monitorhost:3001
      - USERS_PATH=http://userhost:3002
      - REDIS_HOST=redishost
      - REDIS_PORT=6379
      - REDIS_BD=0
      - REDIS_CHANNEL=metrics
      - RES_OK=50
    networks:
      - public_net
    depends_on:
      - redis-server
    
  monitor:
    build: monitor/
    hostname: monitorhost
    ports:
      - "3001:3001"
    environment:
      - VERSION=1.0
      - CLIENTE_PATH=http://clientehost:3000
      - REDIS_HOST=redishost
      - REDIS_PORT=6379
      - REDIS_BD=0
      - CODIGOS_INDISPONIBILIDAD=408,500
      - TIEMPO_INDISPONIBILIDAD=1500
      - REDIS_CHANNEL=metrics
    networks:
      - public_net
    depends_on:
      - redis-server

  kong-dbless:
    image: kong/kong-gateway:3.7.1.2
    hostname: kong
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA: 
    volumes:
      - kong_declarative:/kong/declarative
    networks:
      - kong_net
      - public_net
    configs:
      - source: kong
        target: /kong/declarative/kong.yml
        mode: 444
    depends_on:
      - clientes
    ports:
      - "80:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8445:8445"
      - "8446:8446"
      - "8447:8447"

  redis-server:
    networks:
      - public_net
    hostname: redishost
    image: "redis:alpine"
    ports:
      - "6379:6379"

  usuarios:
    build: usuarios/
    hostname: userhost
    ports:
      - "3002:3002"
    environment:
      - VERSION=1.0
      - USERS_PATH=http://userhost:3002
      - REDIS_HOST=redishost
      - REDIS_PORT=6379
      - REDIS_BD=0
      - REDIS_CHANNEL=accesos
      - PATHS_AUTORIZADOS=/users,/usuario/autentica,/users/autentica,/usuario/autoriza,/users/autoriza,/usuario/revocar,/users/revocar,/clientes,/
    depends_on:
      - redis-server
    networks:
      - public_net

networks:
  kong_net:
  public_net:
  locust_net:

volumes:
  kong_declarative:

configs:
  kong:
    file: ./gateway/kong.yml